### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Krutonium** [PFCKrutonium/OpenRCT2-OpenScenarios#2]
Which one is most appropriate, do you think?

**Comment by IntelOrca** [comment]
Creative commons?

**Comment by Krutonium** [comment]
Unless someone voices an objection, I'm going to stick that on as the licence.

**Comment by LRFLEW** [comment]
CC is a great license for non-code stuff. (I think OpenGraphics should be CC, as GPL is not designed for that). It's worth asking WHICH CC we want here.

The ND clause doesn't make too much sense here (particularly for an "open" project), and CC0 might end up discouraging submissions, so that leaves four options: [CC-BY](http://creativecommons.org/licenses/by/4.0/), [CC-BY-NC](http://creativecommons.org/licenses/by-nc/4.0/), [CC-BY-SA](http://creativecommons.org/licenses/by-sa/4.0/), and [CC-BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/4.0/).

CC-BY-NC-SA is the most like GPL*, so it might be best to go with that. However, there are reasons to choose one of the other ones. It might be a good idea to get feedback from potential contributors before locking down on one.

\* Technically, GPL doesn't have a non-commercial clause, making it more like CC-BY-SA, but most people treat it as if it has one, so CC-BY-NC-SA is more commonly compared to GPL.

**Comment by Krutonium** [comment]
@LRFLEW Opinion on `Creative Commons Attribution 4.0` as seen [Here](https://creativecommons.org/licenses/by/4.0/)?

**Comment by LRFLEW** [comment]
That's the CC-BY one (It says that in parenthesis on the page you linked). I listed that as one of the four options. The modifiers may be nice to have (SA in particular), but I'd say it's up to what the contributors want.

**Comment by Krutonium** [comment]
Is it possible to mix and match the licences, per scenario, but still be able to distribute them as a package?

We could make a file that lists which files are in which licence if so.

**Comment by LRFLEW** [comment]
I mean, maybe. It would be nice to have a flat license that all contributors agree to. The user could also specify an additional license to submit it under (additional instead of alternative so that all scenarios can be distributed with one license).

If we did that, we'd probably want to make the project as a whole the least permissive one (CC-BY-NC-SA), but also include a text file for contributors to specify any alternative licenses they wish to distribute under (so they can dual-license under the projects CC-BY-NC-SA and their own CC-BY if they don't care about the NC or SA attributes).

**Comment by Mailaender** [comment]
> CC-BY-NC-SA is the most like GPL*

Actually not. The https://wiki.creativecommons.org/wiki/NonCommercial is very problematic in terms of open content and free software. Also currently what is meant by "non commercial" is legally undefined so no one can really use and distribute it. I would advise against it. Better use CC-BY-SA.

**Comment by LRFLEW** [comment]
On a second look, I have to agree with @Mailaender. According to [this page](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/), CC BY-SA 4.0 is compatible with GPL 3.0 (OpenRCT2's license). Also, GNU doesn't consider CC BY-NC-SA to be nonfree, so we should probably avoid it. Making all contributors license their contributions under CC BY-SA 4.0, while allowing them the option to release under CC BY 4.0 should work just fine.

**Comment by Krutonium** [comment]
Hm, I think I am going to go with BY-SA then. Thanks for your input!
