### ISSUE TITLE
Luciferous Woods

### ISSUE THREAD

**Issue by enochmeow** [PFCKrutonium/OpenRCT2-OpenScenarios#3]
[Luciferous Woods.zip](https://github.com/PFCKrutonium/OpenRCT2-OpenScenarios/files/1131889/Luciferous.Woods.zip)

**Comment by Krutonium** [comment]
I'm sorry it took me a while to get to this >.<

>- a few custom footpaths (these are the only custom features)

This is my only concern - If you could either (A) Produce a version of this scenario without those paths or (B) get direct permission from the creator of those paths, then I could accept it. TBH I would prefer (A) because it makes it easier to distribute.
